"""empty message

Revision ID: 0f08ccd9760b
Revises: dc1ec39a9244
Create Date: 2023-05-04 21:26:11.818559

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0f08ccd9760b'
down_revision = 'dc1ec39a9244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.alter_column('imdb',
               existing_type=mysql.DECIMAL(precision=2, scale=0),
               type_=sa.Numeric(precision=2, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.alter_column('imdb',
               existing_type=sa.Numeric(precision=2, scale=2),
               type_=mysql.DECIMAL(precision=2, scale=0),
               existing_nullable=True)

    # ### end Alembic commands ###
