"""empty message

Revision ID: d5e4ebf35183
Revises: e3edb052adb4
Create Date: 2023-05-06 11:20:00.435978

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd5e4ebf35183'
down_revision = 'e3edb052adb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('producer_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('movie_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'producer', ['producer_id'], ['id'])
        batch_op.drop_column('producer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('producer', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('movie_ibfk_1', 'producer', ['producer'], ['id'])
        batch_op.drop_column('producer_id')

    # ### end Alembic commands ###
